export default {
  "array-callback-return": [
    "error",
    {
      allowImplicit: false,
      checkForEach: false,
      allowVoid: false,
    },
  ],
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": ["error", { allowImplicit: false }],
  "no-async-promise-executor": "error",
  "no-await-in-loop": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": ["error", "except-parens"],
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": ["error", { checkLoops: "allExceptWhileTrue" }],
  "no-constructor-return": "off",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-duplicate-imports": ["error", { includeExports: true }],
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-fallthrough": ["error", { allowEmptyCase: true }],
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": "off",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-native-nonconstructor": "error",
  "no-obj-calls": "error",
  "no-promise-executor-return": "off",
  "no-prototype-builtins": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "warn",
  "no-this-before-super": "error",
  "no-undef": "error",
  "no-global-assign": "error",
  "no-redeclare": "error",
  "no-unexpected-multiline": "error",
  "no-unmodified-loop-condition": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "warn",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": [
    "error",
    { disallowArithmeticOperators: true },
  ],
  "no-unused-private-class-members": "error",
  "no-unused-vars": "error",
  "no-use-before-define": "error",
  "no-useless-assignment": "error",
  "no-useless-backreference": "error",
  "require-atomic-updates": "error",
  "use-isnan": [
    "error",
    {
      enforceForSwitchCase: true,
      enforceForIndexOf: false,
    },
  ],
  "valid-typeof": "error",
  camelcase: [
    "error",
    {
      properties: "always",
      ignoreDestructuring: true,
    },
  ],
  "default-case-last": "error",
  "default-param-last": "error",
  eqeqeq: ["error", "always", { null: "ignore" }],
  "grouped-accessor-pairs": ["warn", "setBeforeGet"],
  "max-classes-per-file": ["warn", 1],
  "max-depth": ["warn", 4],
  "no-alert": "warn",
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-console": [
    "error",
    {
      // NOTE: this should not be an error for node.js projects because you are frequently logging to the console
      allow: ["warn", "error"],
    },
  ],
  "no-delete-var": "error",
  "no-div-regex": "error",
  "no-else-return": ["warn", { allowElseIf: false }],
  "no-empty": ["error", { allowEmptyCatch: true }],
  "no-empty-function": ["warn", { allow: ["constructors"] }],
  "no-empty-static-block": "error",
  "no-eq-null": "off",
  "no-eval": "error",
  "no-extend-native": "off",
  "no-extra-bind": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-label": "error",
  "no-implicit-coercion": [
    "error",
    {
      boolean: true,
      number: true,
      string: true,
      disallowTemplateShorthand: false,
    },
  ],
  "no-implicit-globals": "warn",
  "no-implied-eval": "error",
  "no-inline-comments": "off",
  "no-invalid-this": "warn",
  "no-iterator": "error",
  "no-label-var": "warn",
  "no-labels": "warn",
  "no-lone-blocks": "off",
  "no-lonely-if": "error",
  "no-loop-func": "warn",
  "no-magic-numbers": [
    "error",
    {
      ignoreArrayIndexes: true,
      ignoreDefaultValues: true,
    },
  ],
  "no-multi-assign": "error",
  "no-multi-str": "warn",
  "no-negated-condition": "warn",
  "no-nested-ternary": "error",
  "no-new": "warn",
  "no-new-func": "warn",
  "no-new-wrappers": "warn",
  "no-nonoctal-decimal-escape": "error",
  "no-object-constructor": "off",
  "no-octal": "error",
  "no-octal-escape": "error",
  "no-param-reassign": "warn",
  "no-plusplus": "off",
  "no-proto": "error",
  "no-regex-spaces": "error",
  "no-restricted-exports": "off",
  "no-restricted-globals": "off",
  "no-restricted-imports": "off",
  "no-restricted-properties": "off",
  "no-restricted-syntax": "off",
  "no-return-assign": "warn",
  "no-script-url": "error",
  "no-sequences": "warn",
  "no-shadow": "error",
  "no-shadow-restricted-names": "error",
  "no-ternary": "off",
  "no-throw-literal": "off",
  "no-undef-init": "warn",
  "no-undefined": "off",
  "no-underscore-dangle": [
    "warn",
    {
      allowAfterThis: true,
      enforceInMethodNames: true,
      enforceInClassFields: true,
      allowInObjectDestructuring: true,
      allowFunctionParams: true,
    },
  ],
  "no-unneeded-ternary": "error",
  "no-unused-expressions": "warn",
  "no-unused-labels": "error",
  "no-useless-call": "error",
  "no-useless-catch": "error",
  "no-useless-computed-key": "warn",
  "no-useless-concat": "warn",
  "no-useless-constructor": "warn",
  "no-useless-escape": "error",
  "no-useless-rename": "warn",
  "no-useless-return": "warn",
  "no-var": "warn",
  "no-void": "off",
  "no-warning-comments": [
    "warn",
    {
      terms: ["todo", "fixme", "bug"],
      location: "start",
    },
  ],
  "no-with": "error",
  "object-shorthand": "warn",
  "one-var": "off",
  "operator-assignment": "off",
  "prefer-arrow-callback": "warn",
  "prefer-const": [
    "warn",
    {
      destructuring: "all",
      ignoreReadBeforeAssign: false,
    },
  ],
  "prefer-destructuring": [
    "warn",
    {
      object: true,
      array: false,
    },
  ],
  "prefer-exponentiation-operator": "off",
  "prefer-named-capture-group": "off",
  "prefer-numeric-literals": "off",
  "prefer-object-has-own": "off",
  "prefer-object-spread": "off",
  "prefer-regex-literals": "off",
  "prefer-rest-params": "warn",
  "prefer-spread": "warn",
  "prefer-template": "warn",
  radix: "off",
  "require-await": "warn",
  "require-unicode-regexp": "warn",
  "require-yield": "error",
  "sort-imports": [
    "warn",
    {
      ignoreCase: false,
      ignoreDeclarationSort: false,
      ignoreMemberSort: false,
      memberSyntaxSortOrder: ["none", "all", "single", "multiple"],
      allowSeparatedGroups: true,
    },
  ],
  "sort-keys": "off",
  "sort-vars": "off",
  strict: "off",
  "symbol-description": "warn",
  "vars-on-top": "warn",
  yoda: "off",
};
